# Generated by Django 4.0 on 2023-08-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='description',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='NoLastName', max_length=100),
            preserve_default=False,
        ),
    ]
